# Generated by Django 3.0.7 on 2020-11-01 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='laptop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('status', models.CharField(choices=[('Approved', 'QA Approved'), ('Denied', 'QA Denied')], default='Sold', max_length=100)),
                ('launch', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='smartphone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('status', models.CharField(choices=[('Approved', 'QA Approved'), ('Denied', 'QA Denied')], default='Sold', max_length=100)),
                ('launch', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
